---
deployment:
  tasks:
    - export DEPLOYPATH=/home/jogjato2/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH && composer install --no-dev --optimize-autoloader
    - cd $DEPLOYPATH && php artisan migrate --force
    - cd $DEPLOYPATH && php artisan storage:link
    - cd $DEPLOYPATH && php artisan config:cache
    - cd $DEPLOYPATH && php artisan route:cache
    - cd $DEPLOYPATH && php artisan view:cache
    - cd $DEPLOYPATH && php artisan filament:cache-components
    - cd $DEPLOYPATH && php artisan queue:restart